version: "3.4"

services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development,
      - LOKI_HOST=http://loki:3100
    networks:
      - net
    depends_on:
      - loki
  
  loki:
    image: grafana/loki:2.2.0
    ports: 
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks: 
      - net

  grafana:
    image: grafana/grafana:7.0.6
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - loki

networks:
  net:
    driver: bridge
